export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCESS = "PRODUCT_LIST_SUCESS";
export const PRODUCT_LIST_FAILD = "PRODUCT_LIST_FAILD";

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
export const SINGLE_PRODUCT_SUCESS = "SINGLE_PRODUCT_SUCESS";
export const SINGLE_PRODUCT_FAILD = "SINGLE_PRODUCT_FAILD";

export const ADD_TO_CART = "ADD_TO_CART";

export const DELETE_TO_CART = "DELETE_TO_CART";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCESS = "USER_REGISTER_SUCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCESS = "USER_SIGNIN_SUCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";

export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCESS = "ORDER_CREATE_SUCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";
export const CART_EMPTY = "CART_EMPTY";
